export const jobPosts = [
  {
    id: 1,
    title: 'Full Stack Developer',
    description: 'Work on web applications.',
    requirements: 'Must have experience in web development, including HTML, CSS, JavaScript, and PHP.',
    salary: '90k-120k',
    lastUpdated: 'Last updated 2 days ago',
    applyLink: 'https://example.com/apply/full-stack-developer',
  },
  {
    id: 2,
    title: 'Data Scientist',
    description: 'Analyze data.',
    requirements: 'Must have experience in data analysis, machine learning, and statistical modeling.',
    salary: '120k-160k',
    lastUpdated: 'Last updated 1 day ago',
    applyLink: 'https://example.com/apply/data-scientist',
  },
  {
    id: 3,
    title: 'UI/UX Designer',
    description: 'Design user interfaces.',
    requirements: 'Must have experience in user interface design, including wireframes, prototypes, and visual design.',
    salary: '70k-90k',
    lastUpdated: 'Last updated 4 hours ago',
    applyLink: 'https://example.com/apply/ui-ux-designer',
  },
  {
    id: 4,
    title: 'Project Manager',
    description: 'Manage projects.',
    requirements: 'Must have experience in project management, including time management, budgeting, and resource allocation.',
    salary: '100k-150k',
    lastUpdated: 'Last updated 3 days ago',
    applyLink: 'https://example.com/apply/project-manager',
  },
  {
    id: 5,
    title: 'Backend Developer',
    description: 'Work on server-side applications.',
    requirements: 'Must have experience in backend development, including Node.js, Python, and Ruby on Rails.',
    salary: '80k-100k',
    lastUpdated: 'Last updated 6 hours ago',
    applyLink: 'https://example.com/apply/backend-developer',
  },
  {
    id: 6,
    title: 'QA Engineer',
    description: 'Test software.',
    requirements: 'Must have experience in software testing, including unit testing, integration testing, and user acceptance testing.',
    salary: '80k-100k',
    lastUpdated: 'Last updated 6 hours ago',
    applyLink: 'https://example.com/apply/qa-engineer',
  },
  {
    id: 7,
    title: 'Android Developer',
    description: 'Work on mobile applications.',
    requirements: 'Must have experience in Android development, including Java, Kotlin, and XML.',
    salary: '140k-190k',
    lastUpdated: 'Last updated 2 days ago',
    applyLink: 'https://example.com/apply/android-developer',
  },
  {
    id: 8,
    title: 'iOS Developer',
    description: 'Work on mobile applications.',
    requirements: 'Must have experience in iOS development, including Swift, Objective-C, and Xcode.',
    salary: '130k-180k',
    lastUpdated: 'Last updated 4 hours ago',
    applyLink: 'https://example.com/apply/ios-developer',
  },
  {
    id: 9,
    title: 'Web Developer',
    description: 'Work on web applications.',
    requirements: 'Must have experience in web development, including HTML, CSS, JavaScript, and PHP.',
    salary: '100k-150k',
    lastUpdated: 'Last updated 1 day ago',
    applyLink: 'https://example.com/apply/web-developer',
  },
  {
    id: 10,
    title: 'Database Administrator',
    description: 'Administer databases.',
    requirements: 'Must have experience in database administration, including MySQL, PostgreSQL, and MongoDB.',
    salary: '110k-150k',
    lastUpdated: 'Last updated 3 days ago',
    applyLink: 'https://example.com/apply/database-administrator',
  },
  {
    id: 11,
    title: 'Digital Marketing Specialist',
    description: 'Elevate our digital marketing strategies to promote our innovative products.',
    requirements: 'Proficiency in SEO, SEM, and social media marketing is highly valued.',
    salary: '80k-110k',
    lastUpdated: 'Last updated 2 days ago',
    applyLink: 'https://example.com/apply/digital-marketing-specialist',
  },
  {
    id: 12,
    title: 'Full Stack Developer',
    description: 'Join our dynamic team to work on cutting-edge technologies.',
    requirements: 'Experience with JavaScript, React, Node.js, and cloud computing is required.',
    salary: '100k-140k',
    lastUpdated: 'Last updated 6 hours ago',
    applyLink: 'https://example.com/apply/full-stack-developer-2',
  },
  {
    id: 13,
    title: 'Data Scientist',
    description: 'Leverage advanced analytics and machine learning to uncover insights from vast data sets.',
    requirements: 'Proficiency with Python and R is a must.',
    salary: '120k-160k',
    lastUpdated: 'Last updated 1 day ago',
    applyLink: 'https://example.com/apply/data-scientist-2',
  },
  {
    id: 14,
    title: 'Customer Support Representative',
    description: 'Deliver unparalleled customer service and support.',
    requirements: 'Exceptional communication skills and a knack for solving problems are key.',
    salary: '50k-70k',
    lastUpdated: 'Last updated 6 hours ago',
    applyLink: 'https://example.com/apply/customer-support-representative',
  },
  {
    id: 15,
    title: 'Project Manager',
    description: 'Guide and coordinate project teams.',
    requirements: 'Strong leadership and organizational skills are necessary.',
    salary: '90k-120k',
    lastUpdated: 'Last updated 2 days ago',
    applyLink: 'https://example.com/apply/project-manager-2',
  }
];
